"""add enquiry processing error

Revision ID: 28033b570164
Revises: 55f81e5d4fea
Create Date: 2026-08-24 13:34:28.807342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28033b570164'
down_revision: Union[str, Sequence[str], None] = '55f81e5d4fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('last_error', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'last_error')
    # ### end Alembic commands ###
