"""align webhook event schema

Revision ID: 55f81e5d4fea
Revises: 44dd1fc77e94
Create Date: 2026-08-24 10:16:28.554696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f81e5d4fea'
down_revision: Union[str, Sequence[str], None] = '44dd1fc77e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_events', 'payload_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('webhook_events', 'status',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('webhook_events', 'signature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'webhook_events',
        sa.Column(
            'signature',
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            server_default='',
        ),
    )
    op.alter_column(
        'webhook_events',
        'signature',
        server_default=None,
    )
    op.alter_column('webhook_events', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('webhook_events', 'payload_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
